apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: portfolio-frontend
  template:
    metadata:
      labels:
        app: portfolio-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 5173
          env:
            - name: VITE_PROXY_TARGET
              value: "{{ .Values.frontend.env.VITE_PROXY_TARGET }}"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: portfolio-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}

